import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gaurab Bhul | MERN Stack Developer",
  description:
    "MERN Stack Developer specializing in React, Next.js, Node.js, Express and MongoDB. I build modern, responsive and scalable web applications.",
  openGraph: {
    title: "Gaurab Bhul | MERN Stack Developer",
    description:
      "MERN Stack Developer specializing in React, Next.js, Node.js, Express and MongoDB. I build modern, responsive and scalable web applications.",
    url: "https://gaurab-portfolio.com",
    type: "website",
  },
=======
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 3add0773ae9da403c44abb48b5a4330893f4b93c
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/jsm-logo.png" sizes="any" />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 3add0773ae9da403c44abb48b5a4330893f4b93c
      </body>
    </html>
  );
}
